### ISSUE TITLE
Add Github to Slack Channel

### ISSUE THREAD

**Issue by bfj5889** [bfj5889/Team_Garnet#3]

**Comment by danquack** [comment]
Here’s a good walk through. https://help.github.com/articles/repository-permission-levels-for-an-organization/

Once you give admin, I can set up the slack. 

--
Daniel Quackenbush
Rochester Institute of Technology
Computer and Information Technologies '18

**Comment by bfj5889** [comment]
I saw that page yesterday when I was trying to promote you guys but I think that only applies to Organizational accounts. I have done some more research and I don't think that you can have admins on regular user accounts.  https://help.github.com/articles/permission-levels-for-a-user-account-repository/
I don't really think we need to make an organizational account (and I don't know if it's free) but it is something we can look into if the team is interested.

**Comment by bfj5889** [comment]
The github should be added to the slack channel now though. I just went ahead and integrated it.
